// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "IOException.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



// valuetype IOException

void
java::io::IOException_Helper::add_ref(::java::io::IOException* _v)
{
  if (_v) _v->_add_ref();
}

void
java::io::IOException_Helper::remove_ref(::java::io::IOException* _v)
{
  if (_v) _v->_remove_ref();
}

java::io::IOException*
java::io::IOException::_downcast(CORBA::ValueBase* _b)
{
  return _b ? (java::io::IOException*)_b->_ptrToValue(_PD_repoId) : 0;
}

const char* java::io::IOException::_PD_repoId = "RMI:java.io.IOException:048A3675A6FD5463:6C8073646525F0AB";

const char*
java::io::IOException::_NP_repositoryId() const
{
  return _PD_repoId;
}

const char*
java::io::IOException::_NP_repositoryId(CORBA::ULong& hash) const
{
  hash = 4027089840U;
  return _PD_repoId;
}

CORBA::Boolean
java::io::IOException::_NP_custom() const
{
  return 0;
}

void*
java::io::IOException::_ptrToValue(const char* _id)
{
  if (_id == ::java::io::IOException::_PD_repoId)
    return (::java::io::IOException*) this;
  
  if (_id == ::java::lang::Exception::_PD_repoId)
    return (::java::lang::Exception*) this;

  if (_id == ::java::lang::Throwable::_PD_repoId)
    return (::java::lang::Throwable*) this;



  if (_id == CORBA::ValueBase::_PD_repoId)
    return (CORBA::ValueBase*) this;
  
  if (omni::strMatch(_id, ::java::io::IOException::_PD_repoId))
    return (::java::io::IOException*) this;
  
  if (omni::strMatch(_id, ::java::lang::Exception::_PD_repoId))
    return (::java::lang::Exception*) this;

  if (omni::strMatch(_id, ::java::lang::Throwable::_PD_repoId))
    return (::java::lang::Throwable*) this;



  if (omni::strMatch(_id, CORBA::ValueBase::_PD_repoId))
    return (CORBA::ValueBase*) this;

  return 0;
}

void
java::io::IOException::_NP_marshal(java::io::IOException* _v, cdrStream& _0s)
{
  omniValueType::marshal(_v, java::io::IOException::_PD_repoId, _0s);
}

void
java::io::IOException_Helper::marshal(::java::io::IOException* _v, cdrStream& _0s)
{
  java::io::IOException::_NP_marshal(_v,_0s);
}

java::io::IOException*
java::io::IOException::_NP_unmarshal(cdrStream& _0s)
{
  CORBA::ValueBase* _b = omniValueType::unmarshal(java::io::IOException::_PD_repoId,
						  4027089840U, 0, _0s);
  java::io::IOException* _d = java::io::IOException::_downcast(_b);
  if (_b && !_d) {
    _b = omniValueType::handleIncompatibleValue(
           java::io::IOException::_PD_repoId,
           4027089840U, _b, (CORBA::CompletionStatus)_0s.completion());
    _d = java::io::IOException::_downcast(_b);
  }
  return _d;
}

java::io::IOException*
java::io::IOException_Helper::unmarshal(cdrStream& _0s)
{
  return java::io::IOException::_NP_unmarshal(_0s);
}

void
java::io::IOException::_PR_marshal_state(cdrStream& _0s) const
{
  ::java::lang::Exception::_PR_marshal_state(_0s);

}

void
java::io::IOException::_PR_unmarshal_state(cdrStream& _0s)
{
  ::java::lang::Exception::_PR_unmarshal_state(_0s);

}

#ifdef OMNI_HAVE_COVARIANT_RETURNS
java::io::IOException*
#else
CORBA::ValueBase*
#endif
java::io::IOException::_copy_value()
{
  CORBA::ValueBase* _b;
  _b = _omni_ValueFactoryManager::create_for_unmarshal(_PD_repoId, 4027089840U);
  java::io::IOException* _v = java::io::IOException::_downcast(_b);
  if (!_v) {
    CORBA::remove_ref(_b);
    OMNIORB_THROW(BAD_PARAM, BAD_PARAM_ValueFactoryFailure,
		  CORBA::COMPLETED_NO);
  }
  _v->_PR_copy_state(this);
  return _v;
}

void
java::io::IOException::_PR_copy_state(java::io::IOException* _v)
{
  ::java::lang::Exception::_PR_copy_state(_v);

}


java::io::IOException::IOException()  {}
java::io::IOException::~IOException() {}

OBV_java::io::IOException::IOException() {}
OBV_java::io::IOException::~IOException() {}

const _omni_ValueIds*
java::io::IOException::_NP_truncatableIds() const
{
  return 0;
}

java::io::IOException_init::IOException_init()  {}
java::io::IOException_init::~IOException_init() {}

java::io::IOException_init*
java::io::IOException_init::_downcast(CORBA::ValueFactory _v)
{
  return _v ? (::java::io::IOException_init*)_v->_ptrToFactory(::java::io::IOException::_PD_repoId) : 0;
}

void*
java::io::IOException_init::_ptrToFactory(const char* _id)
{
  if (_id == ::java::io::IOException::_PD_repoId)
    return (::java::io::IOException_init*) this;
  
  if (_id == CORBA::ValueBase::_PD_repoId)
    return (CORBA::ValueFactoryBase*) this;
  
  if (omni::strMatch(_id, ::java::io::IOException::_PD_repoId))
    return (::java::io::IOException_init*) this;
  
  if (omni::strMatch(_id, CORBA::ValueBase::_PD_repoId))
    return (CORBA::ValueFactoryBase*) this;

  return 0;
}

