// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __IOEx_hh__
#define __IOEx_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_IOEx
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_IOEx
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_IOEx
#endif



#ifndef __seq1__StackTraceElement_hh_EXTERNAL_GUARD__
#define __seq1__StackTraceElement_hh_EXTERNAL_GUARD__
#include <seq1_StackTraceElement.hh>
#endif
#ifndef __corbaidl_hh_EXTERNAL_GUARD__
#define __corbaidl_hh_EXTERNAL_GUARD__
#include <corbaidl.hh>
#endif
#ifndef __boxes_hh_EXTERNAL_GUARD__
#define __boxes_hh_EXTERNAL_GUARD__
#include <boxes.hh>
#endif
#ifndef __StackTraceElement_hh_EXTERNAL_GUARD__
#define __StackTraceElement_hh_EXTERNAL_GUARD__
#include <StackTraceElement.hh>
#endif
#ifndef __Throwable_hh_EXTERNAL_GUARD__
#define __Throwable_hh_EXTERNAL_GUARD__
#include <Throwable.hh>
#endif
#ifndef __Exception_hh_EXTERNAL_GUARD__
#define __Exception_hh_EXTERNAL_GUARD__
#include <Exception.hh>
#endif
#ifndef __IOException_hh_EXTERNAL_GUARD__
#define __IOException_hh_EXTERNAL_GUARD__
#include <IOException.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE java

_CORBA_MODULE_BEG

  _CORBA_MODULE io

  _CORBA_MODULE_BEG

#ifndef __java_mio_mIOException__
#define __java_mio_mIOException__

    class IOException;

    class IOException_Helper {
    public:
      static void add_ref(IOException*);
      static void remove_ref(IOException*);
      static void marshal(IOException*, cdrStream&);
      static IOException* unmarshal(cdrStream&);
    };

    typedef _CORBA_Value_Var    <IOException,IOException_Helper> IOException_var;
    typedef _CORBA_Value_Member <IOException,IOException_Helper> IOException_member;
    typedef _CORBA_Value_OUT_arg<IOException,IOException_Helper> IOException_out;

#endif // __java_mio_mIOException__

  _CORBA_MODULE_END

_CORBA_MODULE_END

_CORBA_MODULE java

_CORBA_MODULE_BEG

  _CORBA_MODULE io

  _CORBA_MODULE_BEG

    class IOEx : public CORBA::UserException {
    public:
      
      IOException_member value;

    

      inline IOEx() {
        pd_insertToAnyFn    = insertToAnyFn;
        pd_insertToAnyFnNCP = insertToAnyFnNCP;
      }
      IOEx(const IOEx&);
      IOEx(IOException* i_value);
      IOEx& operator=(const IOEx&);
      virtual ~IOEx();
      virtual void _raise() const;
      static IOEx* _downcast(CORBA::Exception*);
      static const IOEx* _downcast(const CORBA::Exception*);
      static inline IOEx* _narrow(CORBA::Exception* _e) {
        return _downcast(_e);
      }
      
      void operator>>=(cdrStream&) const ;
      void operator<<=(cdrStream&) ;

      static _core_attr insertExceptionToAny    insertToAnyFn;
      static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

      virtual CORBA::Exception* _NP_duplicate() const;

      static _core_attr const char* _PD_repoId;
      static _core_attr const char* _PD_typeId;

    private:
      virtual const char* _NP_typeId() const;
      virtual const char* _NP_repoId(int*) const;
      virtual void _NP_marshal(cdrStream&) const;
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_java
_CORBA_MODULE_BEG

  _CORBA_MODULE io
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END

_CORBA_MODULE POA_java
_CORBA_MODULE_BEG

  _CORBA_MODULE io
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_java
_CORBA_MODULE_BEG

  _CORBA_MODULE io
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END

_CORBA_MODULE OBV_java
_CORBA_MODULE_BEG

  _CORBA_MODULE io
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_IOEx
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_IOEx
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_IOEx
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_IOEx
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_IOEx
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_IOEx
#endif

#endif  // __IOEx_hh__

