// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __IOException_hh__
#define __IOException_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_IOException
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_IOException
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_IOException
#endif



#ifndef __seq1__StackTraceElement_hh_EXTERNAL_GUARD__
#define __seq1__StackTraceElement_hh_EXTERNAL_GUARD__
#include <seq1_StackTraceElement.hh>
#endif
#ifndef __corbaidl_hh_EXTERNAL_GUARD__
#define __corbaidl_hh_EXTERNAL_GUARD__
#include <corbaidl.hh>
#endif
#ifndef __boxes_hh_EXTERNAL_GUARD__
#define __boxes_hh_EXTERNAL_GUARD__
#include <boxes.hh>
#endif
#ifndef __StackTraceElement_hh_EXTERNAL_GUARD__
#define __StackTraceElement_hh_EXTERNAL_GUARD__
#include <StackTraceElement.hh>
#endif
#ifndef __Throwable_hh_EXTERNAL_GUARD__
#define __Throwable_hh_EXTERNAL_GUARD__
#include <Throwable.hh>
#endif
#ifndef __Exception_hh_EXTERNAL_GUARD__
#define __Exception_hh_EXTERNAL_GUARD__
#include <Exception.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE java

_CORBA_MODULE_BEG

  _CORBA_MODULE io

  _CORBA_MODULE_BEG

#ifndef __java_mio_mIOException__
#define __java_mio_mIOException__

    class IOException;

    class IOException_Helper {
    public:
      static void add_ref(IOException*);
      static void remove_ref(IOException*);
      static void marshal(IOException*, cdrStream&);
      static IOException* unmarshal(cdrStream&);
    };

    typedef _CORBA_Value_Var    <IOException,IOException_Helper> IOException_var;
    typedef _CORBA_Value_Member <IOException,IOException_Helper> IOException_member;
    typedef _CORBA_Value_OUT_arg<IOException,IOException_Helper> IOException_out;

#endif // __java_mio_mIOException__

    class IOException : 
      public virtual lang::Exception
    {
    public:  
      // Standard mapping
      typedef IOException*    _ptr_type;
      typedef IOException_var _var_type;

      static _ptr_type _downcast (CORBA::ValueBase*);
      

#ifdef OMNI_HAVE_COVARIANT_RETURNS
      virtual IOException* _copy_value();
#else
      virtual CORBA::ValueBase* _copy_value();
#endif

      // Definitions in this scope
      

      // Operations and attributes
      

      // Accessors for public members
      

    protected:
      // Accessors for private members
      

    public:
      // omniORB internal
      virtual const char* _NP_repositoryId() const;
      virtual const char* _NP_repositoryId(CORBA::ULong& _hashval) const;

      virtual const _omni_ValueIds* _NP_truncatableIds() const;

      virtual CORBA::Boolean _NP_custom() const;

      virtual void* _ptrToValue(const char* id);

      static void _NP_marshal(IOException*, cdrStream&);
      static IOException* _NP_unmarshal(cdrStream&);
      

      virtual void _PR_marshal_state(cdrStream&) const;
      virtual void _PR_unmarshal_state(cdrStream&);
      virtual void _PR_copy_state(IOException*);

      static _core_attr const char* _PD_repoId;

    protected:
      IOException();
      virtual ~IOException();

    private:
      // Not implemented
      IOException(const IOException &);
      void operator=(const IOException &);
    };

    class IOException_init : public CORBA::ValueFactoryBase
    {
    public:
      virtual ~IOException_init();

      virtual IOException* create__() = 0;
      virtual IOException* create__CORBA_WStringValue(CORBA::WStringValue* arg0) = 0;

      static IOException_init* _downcast(CORBA::ValueFactory _v);
      virtual void* _ptrToFactory(const char* _id);
    protected:
      IOException_init();
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_java
_CORBA_MODULE_BEG

  _CORBA_MODULE io
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_java
_CORBA_MODULE_BEG

  _CORBA_MODULE io
  _CORBA_MODULE_BEG

    class IOException :
      public virtual java::io::IOException,
      public virtual lang::Exception
    {
    protected:
      IOException();
      
      virtual ~IOException();

    public:
      

    protected:
      

    private:
      
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_IOException
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_IOException
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_IOException
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_IOException
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_IOException
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_IOException
#endif

#endif  // __IOException_hh__

