// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "RemoteOutputStream.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



com::healthmarketscience::rmiio::RemoteOutputStream_ptr com::healthmarketscience::rmiio::RemoteOutputStream_Helper::_nil() {
  return ::com::healthmarketscience::rmiio::RemoteOutputStream::_nil();
}

CORBA::Boolean com::healthmarketscience::rmiio::RemoteOutputStream_Helper::is_nil(::com::healthmarketscience::rmiio::RemoteOutputStream_ptr p) {
  return CORBA::is_nil(p);

}

void com::healthmarketscience::rmiio::RemoteOutputStream_Helper::release(::com::healthmarketscience::rmiio::RemoteOutputStream_ptr p) {
  CORBA::release(p);
}

void com::healthmarketscience::rmiio::RemoteOutputStream_Helper::marshalObjRef(::com::healthmarketscience::rmiio::RemoteOutputStream_ptr obj, cdrStream& s) {
  ::com::healthmarketscience::rmiio::RemoteOutputStream::_marshalObjRef(obj, s);
}

com::healthmarketscience::rmiio::RemoteOutputStream_ptr com::healthmarketscience::rmiio::RemoteOutputStream_Helper::unmarshalObjRef(cdrStream& s) {
  return ::com::healthmarketscience::rmiio::RemoteOutputStream::_unmarshalObjRef(s);
}

void com::healthmarketscience::rmiio::RemoteOutputStream_Helper::duplicate(::com::healthmarketscience::rmiio::RemoteOutputStream_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

com::healthmarketscience::rmiio::RemoteOutputStream_ptr
com::healthmarketscience::rmiio::RemoteOutputStream::_duplicate(::com::healthmarketscience::rmiio::RemoteOutputStream_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

com::healthmarketscience::rmiio::RemoteOutputStream_ptr
com::healthmarketscience::rmiio::RemoteOutputStream::_narrow(CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


com::healthmarketscience::rmiio::RemoteOutputStream_ptr
com::healthmarketscience::rmiio::RemoteOutputStream::_unchecked_narrow(CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

com::healthmarketscience::rmiio::RemoteOutputStream_ptr
com::healthmarketscience::rmiio::RemoteOutputStream::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_RemoteOutputStream _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_RemoteOutputStream* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_RemoteOutputStream;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId = "RMI:com.healthmarketscience.rmiio.RemoteOutputStream:0000000000000000";


com::healthmarketscience::rmiio::_objref_RemoteOutputStream::~_objref_RemoteOutputStream() {
  
}


com::healthmarketscience::rmiio::_objref_RemoteOutputStream::_objref_RemoteOutputStream(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
com::healthmarketscience::rmiio::_objref_RemoteOutputStream::_ptrToObjRef(const char* id)
{
  if( id == ::com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId )
    return (::com::healthmarketscience::rmiio::RemoteOutputStream_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId) )
    return (::com::healthmarketscience::rmiio::RemoteOutputStream_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void_e_cjava_mio_mIOEx
class _0RL_cd_D56D3E0763E79EF9_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_D56D3E0763E79EF9_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  
    
  void userException(cdrStream&,_OMNI_NS(IOP_C)*,const char*);
  static const char* const _user_exns[];

  
};

const char* const _0RL_cd_D56D3E0763E79EF9_00000000::_user_exns[] = {
  java::io::IOEx::_PD_repoId
};

void _0RL_cd_D56D3E0763E79EF9_00000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if ( omni::strMatch(repoId, java::io::IOEx::_PD_repoId) ) {
    java::io::IOEx _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_D56D3E0763E79EF9_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  
  com::healthmarketscience::rmiio::_impl_RemoteOutputStream* impl = (com::healthmarketscience::rmiio::_impl_RemoteOutputStream*) svnt->_ptrToInterface(com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId);
#ifdef HAS_Cplusplus_catch_exception_by_base
  impl->flush();
#else
  if (!cd->is_upcall())
    impl->flush();
  else {
    try {
      impl->flush();
    }
    catch(java::io::IOEx& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void com::healthmarketscience::rmiio::_objref_RemoteOutputStream::flush()
{
  _0RL_cd_D56D3E0763E79EF9_00000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_10000000, "flush", 6);


  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_e_cjava_mio_mIOEx
class _0RL_cd_D56D3E0763E79EF9_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_D56D3E0763E79EF9_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&,_OMNI_NS(IOP_C)*,const char*);
  static const char* const _user_exns[];

  CORBA::Boolean result;
};

void _0RL_cd_D56D3E0763E79EF9_20000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_D56D3E0763E79EF9_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_D56D3E0763E79EF9_20000000::_user_exns[] = {
  java::io::IOEx::_PD_repoId
};

void _0RL_cd_D56D3E0763E79EF9_20000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if ( omni::strMatch(repoId, java::io::IOEx::_PD_repoId) ) {
    java::io::IOEx _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_D56D3E0763E79EF9_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_D56D3E0763E79EF9_20000000* tcd = (_0RL_cd_D56D3E0763E79EF9_20000000*)cd;
  com::healthmarketscience::rmiio::_impl_RemoteOutputStream* impl = (com::healthmarketscience::rmiio::_impl_RemoteOutputStream*) svnt->_ptrToInterface(com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId);
#ifdef HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->usingGZIPCompression();
#else
  if (!cd->is_upcall())
    tcd->result = impl->usingGZIPCompression();
  else {
    try {
      tcd->result = impl->usingGZIPCompression();
    }
    catch(java::io::IOEx& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

CORBA::Boolean com::healthmarketscience::rmiio::_objref_RemoteOutputStream::usingGZIPCompression()
{
  _0RL_cd_D56D3E0763E79EF9_20000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_30000000, "usingGZIPCompression", 21);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  void_i_cboolean_e_cjava_mio_mIOEx
class _0RL_cd_D56D3E0763E79EF9_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_D56D3E0763E79EF9_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  void userException(cdrStream&,_OMNI_NS(IOP_C)*,const char*);
  static const char* const _user_exns[];

  CORBA::Boolean arg_0;
};

void _0RL_cd_D56D3E0763E79EF9_40000000::marshalArguments(cdrStream& _n)
{
  _n.marshalBoolean(arg_0);

}

void _0RL_cd_D56D3E0763E79EF9_40000000::unmarshalArguments(cdrStream& _n)
{
  arg_0 = _n.unmarshalBoolean();

}

const char* const _0RL_cd_D56D3E0763E79EF9_40000000::_user_exns[] = {
  java::io::IOEx::_PD_repoId
};

void _0RL_cd_D56D3E0763E79EF9_40000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if ( omni::strMatch(repoId, java::io::IOEx::_PD_repoId) ) {
    java::io::IOEx _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_D56D3E0763E79EF9_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_D56D3E0763E79EF9_40000000* tcd = (_0RL_cd_D56D3E0763E79EF9_40000000*)cd;
  com::healthmarketscience::rmiio::_impl_RemoteOutputStream* impl = (com::healthmarketscience::rmiio::_impl_RemoteOutputStream*) svnt->_ptrToInterface(com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId);
#ifdef HAS_Cplusplus_catch_exception_by_base
  impl->close(tcd->arg_0);
#else
  if (!cd->is_upcall())
    impl->close(tcd->arg_0);
  else {
    try {
      impl->close(tcd->arg_0);
    }
    catch(java::io::IOEx& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void com::healthmarketscience::rmiio::_objref_RemoteOutputStream::close(CORBA::Boolean writeSuccess)
{
  _0RL_cd_D56D3E0763E79EF9_40000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_50000000, "close", 6);
  _call_desc.arg_0 = writeSuccess;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  void_i_corg_momg_mboxedRMI_mseq1__octet_i_clong_e_cjava_mio_mIOEx
class _0RL_cd_D56D3E0763E79EF9_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_D56D3E0763E79EF9_60000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    containsValues(1);
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  void userException(cdrStream&,_OMNI_NS(IOP_C)*,const char*);
  static const char* const _user_exns[];

  org::omg::boxedRMI::seq1_octet_var arg_0_;
  org::omg::boxedRMI::seq1_octet* arg_0;
  CORBA::Long arg_1;
};

void _0RL_cd_D56D3E0763E79EF9_60000000::marshalArguments(cdrStream& _n)
{
  org::omg::boxedRMI::seq1_octet::_NP_marshal(arg_0,_n);
  arg_1 >>= _n;

}

void _0RL_cd_D56D3E0763E79EF9_60000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = org::omg::boxedRMI::seq1_octet::_NP_unmarshal(_n);
  arg_0 = arg_0_.in();
  (CORBA::Long&)arg_1 <<= _n;

}

const char* const _0RL_cd_D56D3E0763E79EF9_60000000::_user_exns[] = {
  java::io::IOEx::_PD_repoId
};

void _0RL_cd_D56D3E0763E79EF9_60000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if ( omni::strMatch(repoId, java::io::IOEx::_PD_repoId) ) {
    java::io::IOEx _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_D56D3E0763E79EF9_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_D56D3E0763E79EF9_60000000* tcd = (_0RL_cd_D56D3E0763E79EF9_60000000*)cd;
  com::healthmarketscience::rmiio::_impl_RemoteOutputStream* impl = (com::healthmarketscience::rmiio::_impl_RemoteOutputStream*) svnt->_ptrToInterface(com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId);
#ifdef HAS_Cplusplus_catch_exception_by_base
  impl->writePacket(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    impl->writePacket(tcd->arg_0, tcd->arg_1);
  else {
    try {
      impl->writePacket(tcd->arg_0, tcd->arg_1);
    }
    catch(java::io::IOEx& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

void com::healthmarketscience::rmiio::_objref_RemoteOutputStream::writePacket(org::omg::boxedRMI::seq1_octet* packet, CORBA::Long packetId)
{
  _0RL_cd_D56D3E0763E79EF9_60000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_70000000, "writePacket", 12);
  _call_desc.arg_0 = packet;
  _call_desc.arg_1 = packetId;

  _invoke(_call_desc);



}
com::healthmarketscience::rmiio::_pof_RemoteOutputStream::~_pof_RemoteOutputStream() {}


omniObjRef*
com::healthmarketscience::rmiio::_pof_RemoteOutputStream::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::com::healthmarketscience::rmiio::_objref_RemoteOutputStream(ior, id);
}


CORBA::Boolean
com::healthmarketscience::rmiio::_pof_RemoteOutputStream::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId) )
    return 1;
  
  return 0;
}

const com::healthmarketscience::rmiio::_pof_RemoteOutputStream _the_pof_com_mhealthmarketscience_mrmiio_mRemoteOutputStream;

com::healthmarketscience::rmiio::_impl_RemoteOutputStream::~_impl_RemoteOutputStream() {}


CORBA::Boolean
com::healthmarketscience::rmiio::_impl_RemoteOutputStream::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "flush") ) {

    _0RL_cd_D56D3E0763E79EF9_00000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_10000000, "flush", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "usingGZIPCompression") ) {

    _0RL_cd_D56D3E0763E79EF9_20000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_30000000, "usingGZIPCompression", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "close") ) {

    _0RL_cd_D56D3E0763E79EF9_40000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_50000000, "close", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "writePacket") ) {

    _0RL_cd_D56D3E0763E79EF9_60000000 _call_desc(_0RL_lcfn_D56D3E0763E79EF9_70000000, "writePacket", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
com::healthmarketscience::rmiio::_impl_RemoteOutputStream::_ptrToInterface(const char* id)
{
  if( id == ::com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId )
    return (::com::healthmarketscience::rmiio::_impl_RemoteOutputStream*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId) )
    return (::com::healthmarketscience::rmiio::_impl_RemoteOutputStream*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
com::healthmarketscience::rmiio::_impl_RemoteOutputStream::_mostDerivedRepoId()
{
  return ::com::healthmarketscience::rmiio::RemoteOutputStream::_PD_repoId;
}

POA_com::healthmarketscience::rmiio::RemoteOutputStream::~RemoteOutputStream() {}

