// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __RemoteFileServer_hh__
#define __RemoteFileServer_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
#endif



#ifndef __IOEx_hh_EXTERNAL_GUARD__
#define __IOEx_hh_EXTERNAL_GUARD__
#include <IOEx.hh>
#endif
#ifndef __seq1__StackTraceElement_hh_EXTERNAL_GUARD__
#define __seq1__StackTraceElement_hh_EXTERNAL_GUARD__
#include <seq1_StackTraceElement.hh>
#endif
#ifndef __corbaidl_hh_EXTERNAL_GUARD__
#define __corbaidl_hh_EXTERNAL_GUARD__
#include <corbaidl.hh>
#endif
#ifndef __boxes_hh_EXTERNAL_GUARD__
#define __boxes_hh_EXTERNAL_GUARD__
#include <boxes.hh>
#endif
#ifndef __StackTraceElement_hh_EXTERNAL_GUARD__
#define __StackTraceElement_hh_EXTERNAL_GUARD__
#include <StackTraceElement.hh>
#endif
#ifndef __Throwable_hh_EXTERNAL_GUARD__
#define __Throwable_hh_EXTERNAL_GUARD__
#include <Throwable.hh>
#endif
#ifndef __Exception_hh_EXTERNAL_GUARD__
#define __Exception_hh_EXTERNAL_GUARD__
#include <Exception.hh>
#endif
#ifndef __IOException_hh_EXTERNAL_GUARD__
#define __IOException_hh_EXTERNAL_GUARD__
#include <IOException.hh>
#endif
#ifndef __seq1__octet_hh_EXTERNAL_GUARD__
#define __seq1__octet_hh_EXTERNAL_GUARD__
#include <seq1_octet.hh>
#endif
#ifndef __RemoteInputStream_hh_EXTERNAL_GUARD__
#define __RemoteInputStream_hh_EXTERNAL_GUARD__
#include <RemoteInputStream.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE com

_CORBA_MODULE_BEG

  _CORBA_MODULE healthmarketscience

  _CORBA_MODULE_BEG

    _CORBA_MODULE rmiio

    _CORBA_MODULE_BEG

#ifndef __com_mhealthmarketscience_mrmiio_mRemoteInputStream__
#define __com_mhealthmarketscience_mrmiio_mRemoteInputStream__

      class RemoteInputStream;
      class _objref_RemoteInputStream;
      class _impl_RemoteInputStream;
      
      typedef _objref_RemoteInputStream* RemoteInputStream_ptr;
      typedef RemoteInputStream_ptr RemoteInputStreamRef;

      class RemoteInputStream_Helper {
      public:
        typedef RemoteInputStream_ptr _ptr_type;

        static _ptr_type _nil();
        static _CORBA_Boolean is_nil(_ptr_type);
        static void release(_ptr_type);
        static void duplicate(_ptr_type);
        static void marshalObjRef(_ptr_type, cdrStream&);
        static _ptr_type unmarshalObjRef(cdrStream&);
      };

      typedef _CORBA_ObjRef_Var<_objref_RemoteInputStream, RemoteInputStream_Helper> RemoteInputStream_var;
      typedef _CORBA_ObjRef_OUT_arg<_objref_RemoteInputStream,RemoteInputStream_Helper > RemoteInputStream_out;

#endif

    _CORBA_MODULE_END

  _CORBA_MODULE_END

_CORBA_MODULE_END

_CORBA_MODULE examples

_CORBA_MODULE_BEG

  _CORBA_MODULE iiop

  _CORBA_MODULE_BEG

#ifndef __examples_miiop_mRemoteFileServer__
#define __examples_miiop_mRemoteFileServer__

    class RemoteFileServer;
    class _objref_RemoteFileServer;
    class _impl_RemoteFileServer;
    
    typedef _objref_RemoteFileServer* RemoteFileServer_ptr;
    typedef RemoteFileServer_ptr RemoteFileServerRef;

    class RemoteFileServer_Helper {
    public:
      typedef RemoteFileServer_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_RemoteFileServer, RemoteFileServer_Helper> RemoteFileServer_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_RemoteFileServer,RemoteFileServer_Helper > RemoteFileServer_out;

#endif

    // interface RemoteFileServer
    class RemoteFileServer {
    public:
      // Declarations for this interface type.
      typedef RemoteFileServer_ptr _ptr_type;
      typedef RemoteFileServer_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_RemoteFileServer :
      public virtual CORBA::Object,
      public virtual omniObjRef
    {
    public:
      void sendFile(com::healthmarketscience::rmiio::RemoteInputStream_ptr arg0);

      inline _objref_RemoteFileServer()  { _PR_setobj(0); }  // nil
      _objref_RemoteFileServer(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_RemoteFileServer();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_RemoteFileServer(const _objref_RemoteFileServer&);
      _objref_RemoteFileServer& operator = (const _objref_RemoteFileServer&);
      // not implemented

      friend class RemoteFileServer;
    };

    class _pof_RemoteFileServer : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_RemoteFileServer() : _OMNI_NS(proxyObjectFactory)(RemoteFileServer::_PD_repoId) {}
      virtual ~_pof_RemoteFileServer();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_RemoteFileServer :
      public virtual omniServant
    {
    public:
      virtual ~_impl_RemoteFileServer();

      virtual void sendFile(com::healthmarketscience::rmiio::RemoteInputStream_ptr arg0) = 0;
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_com
_CORBA_MODULE_BEG

  _CORBA_MODULE healthmarketscience
  _CORBA_MODULE_BEG

    _CORBA_MODULE rmiio
    _CORBA_MODULE_BEG

    _CORBA_MODULE_END

  _CORBA_MODULE_END

_CORBA_MODULE_END

_CORBA_MODULE POA_examples
_CORBA_MODULE_BEG

  _CORBA_MODULE iiop
  _CORBA_MODULE_BEG

    class RemoteFileServer :
      public virtual examples::iiop::_impl_RemoteFileServer,
      public virtual PortableServer::ServantBase
    {
    public:
      virtual ~RemoteFileServer();

      inline ::examples::iiop::RemoteFileServer_ptr _this() {
        return (::examples::iiop::RemoteFileServer_ptr) _do_this(::examples::iiop::RemoteFileServer::_PD_repoId);
      }
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_com
_CORBA_MODULE_BEG

  _CORBA_MODULE healthmarketscience
  _CORBA_MODULE_BEG

    _CORBA_MODULE rmiio
    _CORBA_MODULE_BEG

    _CORBA_MODULE_END

  _CORBA_MODULE_END

_CORBA_MODULE_END

_CORBA_MODULE OBV_examples
_CORBA_MODULE_BEG

  _CORBA_MODULE iiop
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
examples::iiop::RemoteFileServer::_marshalObjRef(::examples::iiop::RemoteFileServer_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_RemoteFileServer
#endif

#endif  // __RemoteFileServer_hh__

