// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "seq1_StackTraceElement.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



// value box seq1_StackTraceElement

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement_Helper::add_ref(::org::omg::boxedRMI::java::lang::seq1_StackTraceElement* _v)
{
  if (_v) _v->_add_ref();
}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement_Helper::remove_ref(::org::omg::boxedRMI::java::lang::seq1_StackTraceElement* _v)
{
  if (_v) _v->_remove_ref();
}

org::omg::boxedRMI::java::lang::seq1_StackTraceElement*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_downcast(CORBA::ValueBase* _b)
{
  return _b ? (org::omg::boxedRMI::java::lang::seq1_StackTraceElement*)_b->_ptrToValue(_PD_repoId) : 0;
}

const char* org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PD_repoId = "RMI:[Ljava.lang.StackTraceElement;:CD38F9930EA8AAEC:6109C59A2636DD85";

const char*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_repositoryId() const
{
  return _PD_repoId;
}

const char*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_repositoryId(CORBA::ULong& hash) const
{
  hash = 581480793U;
  return _PD_repoId;
}

const _omni_ValueIds*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_truncatableIds() const
{
  return 0;
}

CORBA::Boolean
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_custom() const
{
  return 0;
}

CORBA::Boolean
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_box() const
{
  return 1;
}

void*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_ptrToValue(const char* _id)
{
  if (_id == ::org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PD_repoId)
    return (::org::omg::boxedRMI::java::lang::seq1_StackTraceElement*) this;
  
  if (_id == CORBA::ValueBase::_PD_repoId)
    return (CORBA::ValueBase*) this;
  
  if (omni::strMatch(_id, ::org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PD_repoId))
    return (::org::omg::boxedRMI::java::lang::seq1_StackTraceElement*) this;
  
  if (omni::strMatch(_id, CORBA::ValueBase::_PD_repoId))
    return (CORBA::ValueBase*) this;

  return 0;
}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_marshal(org::omg::boxedRMI::java::lang::seq1_StackTraceElement* _v, cdrStream& _0s)
{
  omniValueType::marshal(_v, org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PD_repoId, _0s);
}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement_Helper::marshal(::org::omg::boxedRMI::java::lang::seq1_StackTraceElement* _v, cdrStream& _0s)
{
  org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_marshal(_v,_0s);
}

org::omg::boxedRMI::java::lang::seq1_StackTraceElement*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_unmarshal(cdrStream& _0s)
{
  CORBA::ValueBase* _b = omniValueType::unmarshal(org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PD_repoId,
						  581480793U, 0, _0s);
  org::omg::boxedRMI::java::lang::seq1_StackTraceElement* _d = org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_downcast(_b);
  if (_b && !_d) {
    CORBA::remove_ref(_b);
    OMNIORB_THROW(BAD_PARAM, BAD_PARAM_ValueFactoryFailure,
		  (CORBA::CompletionStatus)_0s.completion());
  }
  return _d;
}

org::omg::boxedRMI::java::lang::seq1_StackTraceElement*
org::omg::boxedRMI::java::lang::seq1_StackTraceElement_Helper::unmarshal(cdrStream& _0s)
{
  return org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_NP_unmarshal(_0s);
}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PR_marshal_state(cdrStream& _0s) const
{
  (const _0RL_boxed_seq1_StackTraceElement&) _pd_boxed >>= _0s;

}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PR_unmarshal_state(cdrStream& _0s)
{
  (_0RL_boxed_seq1_StackTraceElement&)_pd_boxed <<= _0s;

}

#ifdef OMNI_HAVE_COVARIANT_RETURNS
org::omg::boxedRMI::java::lang::seq1_StackTraceElement*
#else
CORBA::ValueBase*
#endif
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_copy_value()
{
  CORBA::ValueBase* _b;
  _b = _omni_ValueFactoryManager::create_for_unmarshal(_PD_repoId, 581480793U);
  org::omg::boxedRMI::java::lang::seq1_StackTraceElement* _v = org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_downcast(_b);
  if (!_v) {
    CORBA::remove_ref(_b);
    OMNIORB_THROW(BAD_PARAM, BAD_PARAM_ValueFactoryFailure,
		  CORBA::COMPLETED_NO);
  }
  _v->_PR_copy_state(this);
  return _v;
}

void
org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PR_copy_state(org::omg::boxedRMI::java::lang::seq1_StackTraceElement* _v)
{
  _pd_boxed = _v->_pd_boxed;
}

org::omg::boxedRMI::java::lang::seq1_StackTraceElement::~seq1_StackTraceElement()
{
  
}

// ValueFactory for value box
class _0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_init : public CORBA::ValueFactoryBase
{
public:
  _0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_init() {}
  virtual ~_0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_init() {}

  virtual CORBA::ValueBase* create_for_unmarshal();
};

CORBA::ValueBase*
_0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_init::create_for_unmarshal()
{
  return new org::omg::boxedRMI::java::lang::seq1_StackTraceElement();
}

class _0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_install {
public:
  _0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_install() {
    CORBA::ValueFactoryBase* vf = new _0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_init();
    _omni_ValueFactoryManager::register_factory(org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PD_repoId, 581480793, vf, 1);
    vf->_remove_ref();
  }
  ~_0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_install() {
    try {
      _omni_ValueFactoryManager::unregister_factory(org::omg::boxedRMI::java::lang::seq1_StackTraceElement::_PD_repoId, 581480793);
    }
    catch (CORBA::BAD_PARAM&) {
    }
  }
};

static _0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_install _0RL_org_omg_boxedRMI_java_lang_seq1_StackTraceElement_install_;

