// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "StackTraceElement.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



// valuetype StackTraceElement

void
java::lang::StackTraceElement_Helper::add_ref(::java::lang::StackTraceElement* _v)
{
  if (_v) _v->_add_ref();
}

void
java::lang::StackTraceElement_Helper::remove_ref(::java::lang::StackTraceElement* _v)
{
  if (_v) _v->_remove_ref();
}

java::lang::StackTraceElement*
java::lang::StackTraceElement::_downcast(CORBA::ValueBase* _b)
{
  return _b ? (java::lang::StackTraceElement*)_b->_ptrToValue(_PD_repoId) : 0;
}

const char* java::lang::StackTraceElement::_PD_repoId = "RMI:java.lang.StackTraceElement:CD38F9930EA8AAEC:6109C59A2636DD85";

const char*
java::lang::StackTraceElement::_NP_repositoryId() const
{
  return _PD_repoId;
}

const char*
java::lang::StackTraceElement::_NP_repositoryId(CORBA::ULong& hash) const
{
  hash = 235518893U;
  return _PD_repoId;
}

CORBA::Boolean
java::lang::StackTraceElement::_NP_custom() const
{
  return 0;
}

void*
java::lang::StackTraceElement::_ptrToValue(const char* _id)
{
  if (_id == ::java::lang::StackTraceElement::_PD_repoId)
    return (::java::lang::StackTraceElement*) this;
  
  

  if (_id == CORBA::ValueBase::_PD_repoId)
    return (CORBA::ValueBase*) this;
  
  if (omni::strMatch(_id, ::java::lang::StackTraceElement::_PD_repoId))
    return (::java::lang::StackTraceElement*) this;
  
  

  if (omni::strMatch(_id, CORBA::ValueBase::_PD_repoId))
    return (CORBA::ValueBase*) this;

  return 0;
}

void
java::lang::StackTraceElement::_NP_marshal(java::lang::StackTraceElement* _v, cdrStream& _0s)
{
  omniValueType::marshal(_v, java::lang::StackTraceElement::_PD_repoId, _0s);
}

void
java::lang::StackTraceElement_Helper::marshal(::java::lang::StackTraceElement* _v, cdrStream& _0s)
{
  java::lang::StackTraceElement::_NP_marshal(_v,_0s);
}

java::lang::StackTraceElement*
java::lang::StackTraceElement::_NP_unmarshal(cdrStream& _0s)
{
  CORBA::ValueBase* _b = omniValueType::unmarshal(java::lang::StackTraceElement::_PD_repoId,
						  235518893U, 0, _0s);
  java::lang::StackTraceElement* _d = java::lang::StackTraceElement::_downcast(_b);
  if (_b && !_d) {
    _b = omniValueType::handleIncompatibleValue(
           java::lang::StackTraceElement::_PD_repoId,
           235518893U, _b, (CORBA::CompletionStatus)_0s.completion());
    _d = java::lang::StackTraceElement::_downcast(_b);
  }
  return _d;
}

java::lang::StackTraceElement*
java::lang::StackTraceElement_Helper::unmarshal(cdrStream& _0s)
{
  return java::lang::StackTraceElement::_NP_unmarshal(_0s);
}

void
java::lang::StackTraceElement::_PR_marshal_state(cdrStream& _0s) const
{
  
}

void
java::lang::StackTraceElement::_PR_unmarshal_state(cdrStream& _0s)
{
  
}

#ifdef OMNI_HAVE_COVARIANT_RETURNS
java::lang::StackTraceElement*
#else
CORBA::ValueBase*
#endif
java::lang::StackTraceElement::_copy_value()
{
  CORBA::ValueBase* _b;
  _b = _omni_ValueFactoryManager::create_for_unmarshal(_PD_repoId, 235518893U);
  java::lang::StackTraceElement* _v = java::lang::StackTraceElement::_downcast(_b);
  if (!_v) {
    CORBA::remove_ref(_b);
    OMNIORB_THROW(BAD_PARAM, BAD_PARAM_ValueFactoryFailure,
		  CORBA::COMPLETED_NO);
  }
  _v->_PR_copy_state(this);
  return _v;
}

void
java::lang::StackTraceElement::_PR_copy_state(java::lang::StackTraceElement* _v)
{
  
}


java::lang::StackTraceElement::StackTraceElement()  {}
java::lang::StackTraceElement::~StackTraceElement() {}

OBV_java::lang::StackTraceElement::StackTraceElement() {}
OBV_java::lang::StackTraceElement::~StackTraceElement() {}

const _omni_ValueIds*
java::lang::StackTraceElement::_NP_truncatableIds() const
{
  return 0;
}

java::lang::StackTraceElement_init::StackTraceElement_init()  {}
java::lang::StackTraceElement_init::~StackTraceElement_init() {}

java::lang::StackTraceElement_init*
java::lang::StackTraceElement_init::_downcast(CORBA::ValueFactory _v)
{
  return _v ? (::java::lang::StackTraceElement_init*)_v->_ptrToFactory(::java::lang::StackTraceElement::_PD_repoId) : 0;
}

void*
java::lang::StackTraceElement_init::_ptrToFactory(const char* _id)
{
  if (_id == ::java::lang::StackTraceElement::_PD_repoId)
    return (::java::lang::StackTraceElement_init*) this;
  
  if (_id == CORBA::ValueBase::_PD_repoId)
    return (CORBA::ValueFactoryBase*) this;
  
  if (omni::strMatch(_id, ::java::lang::StackTraceElement::_PD_repoId))
    return (::java::lang::StackTraceElement_init*) this;
  
  if (omni::strMatch(_id, CORBA::ValueBase::_PD_repoId))
    return (CORBA::ValueFactoryBase*) this;

  return 0;
}

